# fly.toml app configuration file generated for escape-fractal-viewer on 2023-09-01T13:55:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "escape-fractal-viewer"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
